/* eslint-disable */
// ---------------------------------------------------------------------------
// FILE GENERATO da scripts/gen_questions.py — non modificare a mano.
//
// Design a confronto a coppie completo (complete paired-comparison):
// 12 temi -> 66 item, ogni coppia di temi confrontata esattamente una volta.
// Ogni tema compare in 11 item, con 11 affermazioni distinte.
// Lati bilanciati (5/6 comparse a sinistra per tema) per neutralizzare il side-bias.
// ---------------------------------------------------------------------------

export type QuestionSeed = {
  position: number;
  leftStatement: string;
  rightStatement: string;
  leftTheme: string;
  rightTheme: string;
  leftWeight?: number;
  rightWeight?: number;
};

export const QUESTIONS: QuestionSeed[] = [
  {
    position: 1,
    leftStatement: "Prima di accettare una tesi chiedo su quali dati si basa",
    rightStatement: "Cerco sempre il punto d'incontro fra posizioni diverse",
    leftTheme: "analitico",
    rightTheme: "armonia",
  },
  {
    position: 2,
    leftStatement: "Percepisco lo stato d'animo degli altri prima che lo dicano",
    rightStatement: "Preferisco improvvisare e correggere strada facendo",
    leftTheme: "empatia",
    rightTheme: "attivatore",
  },
  {
    position: 3,
    leftStatement: "Mi entusiasmano le idee nuove più della loro esecuzione",
    rightStatement: "Quando prometto qualcosa, per me diventa un obbligo morale",
    leftTheme: "ideazione",
    rightTheme: "responsabilita",
  },
  {
    position: 4,
    leftStatement: "Sento il bisogno di chiudere qualcosa di concreto ogni singolo giorno",
    rightStatement: "Mi viene naturale spiegare le cose in modo che tutti capiscano",
    leftTheme: "realizzatore",
    rightTheme: "comunicazione",
  },
  {
    position: 5,
    leftStatement: "Le discussioni accese mi sembrano spesso energia sprecata",
    rightStatement: "Vedo negli altri il potenziale che loro non vedono ancora",
    leftTheme: "armonia",
    rightTheme: "sviluppatore",
  },
  {
    position: 6,
    leftStatement: "Dopo dieci minuti di analisi mi chiedo quando si parte",
    rightStatement: "Mi dà energia il passaggio dal non sapere al sapere",
    leftTheme: "attivatore",
    rightTheme: "apprendimento",
  },
  {
    position: 7,
    leftStatement: "Uso storie ed esempi concreti per far arrivare un concetto",
    rightStatement: "So di poter gestire quasi qualunque situazione mi capiti",
    leftTheme: "comunicazione",
    rightTheme: "fiducia-in-se",
  },
  {
    position: 8,
    leftStatement: "A fine settimana misuro il mio valore da quanto ho prodotto",
    rightStatement: "Cerco sempre la causa che sta dietro a un risultato",
    leftTheme: "realizzatore",
    rightTheme: "analitico",
  },
  {
    position: 9,
    leftStatement: "Studio volentieri argomenti che non mi servono subito",
    rightStatement: "Preferisco cedere su un dettaglio che incrinare un rapporto",
    leftTheme: "apprendimento",
    rightTheme: "armonia",
  },
  {
    position: 10,
    leftStatement: "Amo pianificare ogni dettaglio prima di iniziare",
    rightStatement: "Imparo molto di più provando che studiando",
    leftTheme: "organizzazione",
    rightTheme: "attivatore",
  },
  {
    position: 11,
    leftStatement: "I progressi di chi affianco mi danno più soddisfazione dei miei",
    rightStatement: "Diffido delle conclusioni tratte da pochi casi",
    leftTheme: "sviluppatore",
    rightTheme: "analitico",
  },
  {
    position: 12,
    leftStatement: "Se un lavoro esce male, sento che la responsabilità è comunque mia",
    rightStatement: "Quando inizio qualcosa di nuovo mi sento nel mio elemento",
    leftTheme: "responsabilita",
    rightTheme: "apprendimento",
  },
  {
    position: 13,
    leftStatement: "Sono io a fare il primo passo quando il gruppo è bloccato",
    rightStatement: "Il lavoro arretrato mi toglie serenità finchè non lo smaltisco",
    leftTheme: "attivatore",
    rightTheme: "realizzatore",
  },
  {
    position: 14,
    leftStatement: "In riunione prendo la parola per chiarire il punto",
    rightStatement: "Mi piace smontare un problema nelle sue componenti",
    leftTheme: "comunicazione",
    rightTheme: "analitico",
  },
  {
    position: 15,
    leftStatement: "Prendo decisioni difficili senza bisogno di conferme",
    rightStatement: "Preferisco fare tardi piuttosto che consegnare qualcosa di incompleto",
    leftTheme: "fiducia-in-se",
    rightTheme: "responsabilita",
  },
  {
    position: 16,
    leftStatement: "Faccio da ponte quando due colleghi non si parlano",
    rightStatement: "Una decisione presa oggi vale più di una perfetta fra un mese",
    leftTheme: "armonia",
    rightTheme: "attivatore",
  },
  {
    position: 17,
    leftStatement: "Ho bisogno di un metodo chiaro per lavorare bene",
    rightStatement: "Preferisco una giornata piena a una giornata leggera",
    leftTheme: "organizzazione",
    rightTheme: "realizzatore",
  },
  {
    position: 18,
    leftStatement: "Le emozioni delle persone attorno a me mi arrivano forte",
    rightStatement: "Preferisco un dato verificato a un'impressione condivisa",
    leftTheme: "empatia",
    rightTheme: "analitico",
  },
  {
    position: 19,
    leftStatement: "Gli altri mi affidano le cose importanti perché sanno che le concludo",
    rightStatement: "Le lunghe riunioni preparatorie mi tolgono energia",
    leftTheme: "responsabilita",
    rightTheme: "attivatore",
  },
  {
    position: 20,
    leftStatement: "Se sono convinto di una scelta, la sostengo anche da solo",
    rightStatement: "Mi metto al lavoro subito, anche se l'obiettivo non è ancora perfetto",
    leftTheme: "fiducia-in-se",
    rightTheme: "realizzatore",
  },
  {
    position: 21,
    leftStatement: "Collego spesso cose che sembrano non c'entrare nulla fra loro",
    rightStatement: "Evito di sollevare obiezioni che non siano davvero decisive",
    leftTheme: "ideazione",
    rightTheme: "armonia",
  },
  {
    position: 22,
    leftStatement: "Mi ritrovo a fare da mentore anche senza un ruolo formale",
    rightStatement: "Le scadenze scritte in calendario mi danno sicurezza",
    leftTheme: "sviluppatore",
    rightTheme: "organizzazione",
  },
  {
    position: 23,
    leftStatement: "Capisco come sta un collega dal tono con cui mi saluta",
    rightStatement: "Non riesco a lasciare un impegno a metà, anche quando non conviene",
    leftTheme: "empatia",
    rightTheme: "responsabilita",
  },
  {
    position: 24,
    leftStatement: "Trovo energia nel guardare la lista delle cose che ho completato",
    rightStatement: "Davanti a un vincolo cerco un modo diverso di vedere il problema",
    leftTheme: "realizzatore",
    rightTheme: "ideazione",
  },
  {
    position: 25,
    leftStatement: "Preferisco un prototipo grezzo a una presentazione impeccabile",
    rightStatement: "Le critiche non mi fanno cambiare rotta facilmente",
    leftTheme: "attivatore",
    rightTheme: "fiducia-in-se",
  },
  {
    position: 26,
    leftStatement: "Metto in ordine le informazioni prima ancora di analizzarle",
    rightStatement: "Un accordo condiviso vale più di una decisione perfetta",
    leftTheme: "organizzazione",
    rightTheme: "armonia",
  },
  {
    position: 27,
    leftStatement: "Ho pazienza autentica con chi impara lentamente",
    rightStatement: "Faccio fatica a stare fermo quando c'è ancora qualcosa da finire",
    leftTheme: "sviluppatore",
    rightTheme: "realizzatore",
  },
  {
    position: 28,
    leftStatement: "Individuo rapidamente i punti deboli di un ragionamento",
    rightStatement: "Genero molte alternative anche quando una soluzione c'è già",
    leftTheme: "analitico",
    rightTheme: "ideazione",
  },
  {
    position: 29,
    leftStatement: "Mi fido del mio giudizio più che del parere della maggioranza",
    rightStatement: "Le persone mi confidano cose personali anche senza conoscermi bene",
    leftTheme: "fiducia-in-se",
    rightTheme: "empatia",
  },
  {
    position: 30,
    leftStatement: "Preferisco insegnare a fare che fare al posto di qualcuno",
    rightStatement: "Mi muovo anche quando non ho tutte le informazioni",
    leftTheme: "sviluppatore",
    rightTheme: "attivatore",
  },
  {
    position: 31,
    leftStatement: "Accumulo corsi, letture e approfondimenti per pura curiosità",
    rightStatement: "Mi annoio quando si ripete sempre lo stesso schema",
    leftTheme: "apprendimento",
    rightTheme: "ideazione",
  },
  {
    position: 32,
    leftStatement: "Mi diverte trovare la frase giusta per riassumere un'idea",
    rightStatement: "Prima di rispondere penso a come si sentira' chi mi ascolta",
    leftTheme: "comunicazione",
    rightTheme: "empatia",
  },
  {
    position: 33,
    leftStatement: "Nei momenti di crisi resto lucido mentre gli altri si agitano",
    rightStatement: "Noto i piccoli miglioramenti delle persone e glieli dico",
    leftTheme: "fiducia-in-se",
    rightTheme: "sviluppatore",
  },
  {
    position: 34,
    leftStatement: "Le mie idee migliori arrivano mentre sto facendo altro",
    rightStatement: "Credo che sia l'azione a creare chiarezza, non la riflessione",
    leftTheme: "ideazione",
    rightTheme: "attivatore",
  },
  {
    position: 35,
    leftStatement: "Preferisco un progetto mai fatto prima a uno che padroneggio",
    rightStatement: "Mi accorgo della tensione in una stanza anche se nessuno parla",
    leftTheme: "apprendimento",
    rightTheme: "empatia",
  },
  {
    position: 36,
    leftStatement: "Mi sento in debito finchè non ho restituito cio' che ho ricevuto",
    rightStatement: "Preparo con cura come dirò le cose, non solo cosa dirò",
    leftTheme: "responsabilita",
    rightTheme: "comunicazione",
  },
  {
    position: 37,
    leftStatement: "Preferisco riformulare la domanda che rispondere a quella data",
    rightStatement: "Preferisco decidere io piuttosto che aspettare un consenso",
    leftTheme: "ideazione",
    rightTheme: "fiducia-in-se",
  },
  {
    position: 38,
    leftStatement: "Faccio fatica a restare indifferente quando qualcuno sta male",
    rightStatement: "Investo tempo su chi è promettente anche se ora rende poco",
    leftTheme: "empatia",
    rightTheme: "sviluppatore",
  },
  {
    position: 39,
    leftStatement: "Il cambiamento mi incuriosisce più di quanto mi preoccupi",
    rightStatement: "Parlare davanti a un pubblico mi dà energia invece che ansia",
    leftTheme: "apprendimento",
    rightTheme: "comunicazione",
  },
  {
    position: 40,
    leftStatement: "Mi accordo sul metodo prima di entrare nel merito",
    rightStatement: "Anche gli impegni presi a voce, per me, contano come contratti",
    leftTheme: "armonia",
    rightTheme: "responsabilita",
  },
  {
    position: 41,
    leftStatement: "Costruisco procedure per non dover ridecidere ogni volta",
    rightStatement: "Scelgo le parole con cura nei momenti delicati",
    leftTheme: "organizzazione",
    rightTheme: "empatia",
  },
  {
    position: 42,
    leftStatement: "Non decido finchè non ho considerato le spiegazioni alternative",
    rightStatement: "Provo i nuovi strumenti prima che diventino uno standard",
    leftTheme: "analitico",
    rightTheme: "apprendimento",
  },
  {
    position: 43,
    leftStatement: "Traduco volentieri il linguaggio tecnico per chi non lo conosce",
    rightStatement: "Mi piace costruire percorsi di crescita su misura",
    leftTheme: "comunicazione",
    rightTheme: "sviluppatore",
  },
  {
    position: 44,
    leftStatement: "Preferisco sacrificarmi piuttosto che deludere chi conta su di me",
    rightStatement: "Mi assegno obiettivi personali anche quando nessuno me li chiede",
    leftTheme: "responsabilita",
    rightTheme: "realizzatore",
  },
  {
    position: 45,
    leftStatement: "Guardo prima cio' che unisce e poi cio' che divide",
    rightStatement: "Non ho bisogno di essere rassicurato per andare avanti",
    leftTheme: "armonia",
    rightTheme: "fiducia-in-se",
  },
  {
    position: 46,
    leftStatement: "Credo che quasi tutti possano migliorare, se ben accompagnati",
    rightStatement: "Mi piace essere principiante, anche se è scomodo",
    leftTheme: "sviluppatore",
    rightTheme: "apprendimento",
  },
  {
    position: 47,
    leftStatement: "Le scelte prese d'istinto mi mettono a disagio",
    rightStatement: "Controllo due volte prima di consegnare, per non lasciare errori ad altri",
    leftTheme: "analitico",
    rightTheme: "responsabilita",
  },
  {
    position: 48,
    leftStatement: "Mi accorgo subito quando un messaggio non è arrivato",
    rightStatement: "Nei conflitti abbasso il tono invece di alzarlo",
    leftTheme: "comunicazione",
    rightTheme: "armonia",
  },
  {
    position: 49,
    leftStatement: "Riesco a mettermi nei panni anche di chi non mi somiglia",
    rightStatement: "Mi piace immaginare scenari che ancora non esistono",
    leftTheme: "empatia",
    rightTheme: "ideazione",
  },
  {
    position: 50,
    leftStatement: "Davanti a un problema il mio primo pensiero è cosa potevo fare io",
    rightStatement: "I cambi di programma mi infastidiscono più dei problemi tecnici",
    leftTheme: "responsabilita",
    rightTheme: "organizzazione",
  },
  {
    position: 51,
    leftStatement: "Quando un'idea mi convince, voglio testarla entro la settimana",
    rightStatement: "Preferisco discutere un'idea a voce piuttosto che per iscritto",
    leftTheme: "attivatore",
    rightTheme: "comunicazione",
  },
  {
    position: 52,
    leftStatement: "Trovo bello un concetto anche prima di sapere se sarà utile",
    rightStatement: "Do volentieri una seconda occasione a chi ha sbagliato",
    leftTheme: "ideazione",
    rightTheme: "sviluppatore",
  },
  {
    position: 53,
    leftStatement: "Trovo soddisfazione nel far tornare i conti",
    rightStatement: "I miei file e i miei spazi seguono una logica precisa",
    leftTheme: "analitico",
    rightTheme: "organizzazione",
  },
  {
    position: 54,
    leftStatement: "Preferisco un gruppo sereno a un gruppo brillante ma teso",
    rightStatement: "Il clima emotivo del team influenza molto il mio lavoro",
    leftTheme: "armonia",
    rightTheme: "empatia",
  },
  {
    position: 55,
    leftStatement: "Approfondisco un tema finchè non ne capisco la struttura",
    rightStatement: "Accetto volentieri la responsabilità di una scelta impopolare",
    leftTheme: "apprendimento",
    rightTheme: "fiducia-in-se",
  },
  {
    position: 56,
    leftStatement: "Preferisco un piano imperfetto a nessun piano",
    rightStatement: "Trovo soddisfazione nel rendere memorabile una presentazione",
    leftTheme: "organizzazione",
    rightTheme: "comunicazione",
  },
  {
    position: 57,
    leftStatement: "Accetto il rischio di sbagliare pur di andare più veloce",
    rightStatement: "Chiedo tempo per verificare prima di dare una risposta",
    leftTheme: "attivatore",
    rightTheme: "analitico",
  },
  {
    position: 58,
    leftStatement: "Considero un successo quando chi ho formato non ha più bisogno di me",
    rightStatement: "Rispetto le regole anche quando nessuno sta guardando",
    leftTheme: "sviluppatore",
    rightTheme: "responsabilita",
  },
  {
    position: 59,
    leftStatement: "Do volentieri voce alle idee del gruppo davanti agli altri",
    rightStatement: "Propongo volentieri strade che nessuno ha ancora considerato",
    leftTheme: "comunicazione",
    rightTheme: "ideazione",
  },
  {
    position: 60,
    leftStatement: "Uso la mia bussola interna più dei riferimenti esterni",
    rightStatement: "Un'idea entusiasmante senza prove per me resta un'ipotesi",
    leftTheme: "fiducia-in-se",
    rightTheme: "analitico",
  },
  {
    position: 61,
    leftStatement: "Un ritmo di lavoro costante è cio' che mi fa sentire in forma",
    rightStatement: "Prima di chiudere voglio che tutti si siano sentiti ascoltati",
    leftTheme: "realizzatore",
    rightTheme: "armonia",
  },
  {
    position: 62,
    leftStatement: "Divido ogni progetto in fasi con responsabili e date",
    rightStatement: "Un brainstorming mi ricarica più di una riunione decisionale",
    leftTheme: "organizzazione",
    rightTheme: "ideazione",
  },
  {
    position: 63,
    leftStatement: "Anche nel tempo libero mi piace portare a termine qualche progetto",
    rightStatement: "Ascolto più quello che non viene detto che le parole",
    leftTheme: "realizzatore",
    rightTheme: "empatia",
  },
  {
    position: 64,
    leftStatement: "Chiedo aiuto solo dopo aver esaurito le mie opzioni",
    rightStatement: "Arrivo puntuale perché ho previsto i tempi in anticipo",
    leftTheme: "fiducia-in-se",
    rightTheme: "organizzazione",
  },
  {
    position: 65,
    leftStatement: "Chiedo 'perché funziona così?' anche fuori dal mio ruolo",
    rightStatement: "Giudico una riunione da quante decisioni operative ne escono",
    leftTheme: "apprendimento",
    rightTheme: "realizzatore",
  },
  {
    position: 66,
    leftStatement: "Mi rassicura sapere in anticipo come sarà la mia settimana",
    rightStatement: "Cambio volentieri campo pur di imparare qualcosa di nuovo",
    leftTheme: "organizzazione",
    rightTheme: "apprendimento",
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
